### PR TITLE
fix(ui): fix RTL layout in list delegates

### LINKED ISSUE #1463: All custom delegate layouts are broken in RTL (Right-to-left) environment
docsets (updates available):
docsets (updates available)

search highlight:
search highlight

search categories:
search categories

### PR DESCRIPTION
**Pull request by ratijas**
After:

image

image

image

Fixes #1463

### CODE REVIEW

File: src/libs/ui/docsetlistitemdelegate.cpp [hunk 1]
```diff
@@ -59,13 +59,19 @@ void DocsetListItemDelegate::paint(QPainter *painter,
     font.setItalic(true);
 
     const QFontMetrics fontMetrics(font);
+    const int margin = 4; // Random small number
```
Comment (trollixx) [inline src/libs/ui/docsetlistitemdelegate.cpp:62]: There's probably margin provided by theme we should use here. I'll look into this later.

**Review by trollixx — APPROVED** [review]
RTL is hard, thanks for working on this!
