### PR TITLE
ui: Fix docset removing on Windows (fixes #621)

### LINKED ISSUE #621: Zeal 0.3.0 remove docset not actually working
In 0.3.0 when remove a docset int the docset manager UI, it gets removed from the list and the main UI. However  files on the disk remain untouched and after restart Zeal the deleted docset just reappear in the list.

My system is Win10, tried portable and non-portable version.

### PR DESCRIPTION
**Pull request by jkozera**
Docsets need to be removed from registry first, to avoid rename() failing when files are in use.

### CODE REVIEW

File: src/libs/ui/docsetsdialog.cpp [hunk 1]
```diff
@@ -693,12 +693,21 @@ void DocsetsDialog::removeDocset(const QString &name)
     const QString tmpPath = docsetPath + QLatin1String(".deleteme.")
             + QString::number(QDateTime::currentMSecsSinceEpoch());
 
-    // Rename first to allow simultaneous installation.
-    // TODO: Check for error
-    QDir().rename(docsetPath, tmpPath);
-
+    // Remove from registry first to avoid renaming files in use on Windows
```
Comment (trollixx) [inline src/libs/ui/docsetsdialog.cpp]: Missing period! :)

File: src/libs/ui/docsetsdialog.cpp [hunk 2]
```diff
@@ -693,12 +693,21 @@ void DocsetsDialog::removeDocset(const QString &name)
...
     m_docsetRegistry->remove(name);
 
+    // Rename first to allow simultaneous installation.
+    if (!QDir().rename(docsetPath, tmpPath)) {
+        const QString error = tr(
```
Comment (trollixx) [inline src/libs/ui/docsetsdialog.cpp]:
```cpp
const QString error = tr("Cannot delete docset <b>%1</b>! Please try closing other "
                         "applications first, as they may be accessing the docset "
                         "files.").arg(title);
```
