### PR TITLE
fix(ui): replace QKeySequence::NextChild with manual shortcut

### LINKED ISSUE #1465: The key sequence 'Ctrl+PgDown' is ambiguous
Ctrl+PgUp and Ctrl+PgDown are two primary shortcuts to switch tabs left and right respectively. Strangely enough, Ctrl+PgUp works fine, but Ctrl+PgDown triggers this error and does nothing:

Zeal - Ctrl+PgDown shortcut

That means somewhere in the code, two instances of QAction registered the same shortcut for themselves, and they fight each other.

### PR DESCRIPTION
**Pull request by ratijas**
Qt internally can not de-duplicate standard shortcuts like QKeySequence::NextChild and manually specified Ctrl+PageDown which are practically the same thing on default KDE/Plasma installations.

Fixes #1465

### CODE REVIEW

File: src/libs/ui/mainwindow.cpp [hunk 1]
```diff
@@ -221,14 +221,15 @@ MainWindow::MainWindow(Core::Application *app, QWidget *parent)
     addAction(ui->actionCloseTab);
     connect(ui->actionCloseTab, &QAction::triggered, this, [this]() { closeTab(); });
 
-    ui->actionNextTab->setShortcuts({QKeySequence::NextChild,
+    // TODO: Use QKeySequence::PreviousChild & NextChild, when QTBUG-112193 is fixed.
```
Comment (trollixx) [inline src/libs/ui/mainwindow.cpp:224]:
```suggestion
    // TODO: Use QKeySequence::NextChild, when QTBUG-112193 is fixed.
```

File: src/libs/ui/mainwindow.cpp [hunk 2]
```diff
@@ -221,14 +221,15 @@ MainWindow::MainWindow(Core::Application *app, QWidget *parent)
...
+    ui->actionNextTab->setShortcuts({QKeySequence(Qt::ControlModifier | Qt::Key_Tab),
                                      QKeySequence(Qt::ControlModifier | Qt::Key_PageDown)});
     addAction(ui->actionNextTab);
     connect(ui->actionNextTab, &QAction::triggered, this, [this]() {
         m_tabBar->setCurrentIndex((m_tabBar->currentIndex() + 1) % m_tabBar->count());
     });
 
-    // TODO: Use QKeySequence::PreviousChild, when QTBUG-15746 is fixed.
+    // TODO: Use QKeySequence::PreviousChild & NextChild, when QTBUG-112193 is fixed.
```
Comment (trollixx) [inline src/libs/ui/mainwindow.cpp:232]:
```suggestion
    // TODO: Use QKeySequence::PreviousChild, when QTBUG-15746 and QTBUG-112193 are fixed.
```

**Review by trollixx — CHANGES_REQUESTED** [review]
Thanks! A couple tiny nits about the to-do comments.

**Review by trollixx — APPROVED** [review]
